version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      - DEBUG=${DEBUG:-False}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - PDFMONKEY_API_KEY=${PDFMONKEY_API_KEY}
      - PDFMONKEY_PREVENTION_TEMPLATE_ID=${PDFMONKEY_PREVENTION_TEMPLATE_ID}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1,railway.app}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-https://railway.app,http://localhost:5173}
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${PORT:-80}:80"
    environment:
      - BACKEND_URL=${BACKEND_URL:-http://backend:8000}
    depends_on:
      - backend

  db:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-pdfcreator} 