# railway.app.toml

[build]
builder = "nixpacks"
buildCommand = "cd frontend && npm install && npm run build && cd .. && pip install -r requirements.txt"

[deploy]
startCommand = "cd backend && python manage.py migrate && gunicorn core.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/api/templates/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[nixpacks]
nodejs-version = "18.17.1"
python-version = "3.9" 