[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
watchPatterns = ["**/*.py", "**/*.tsx", "**/*.ts", "**/*.js", "**/*.jsx"]

[deploy]
healthcheckPath = "/api/templates/"
restartPolicyType = "ON_FAILURE"
numReplicas = 1 